### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by daris** [ezyang/git-ftp#81]
```
Remote Path: /
Use SSL? n
Should I write ftp details to .git/ftpdata? y
INFO: Base directory is /
Traceback (most recent call last):
    File "/Users/programista/bin/git-ftp.py", line 489, in <module>
        main()
    File "/Users/programista/bin/git-ftp.py", line 163, in main
        gitftpignore = os.path.join(repo.working_dir, options.ftp.gitftpignore)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 75, in join
        if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I got this after configuring ftp details. Running again git-ftp.py worked (it uploaded new changes). OSX Yosemite

**Comment by muellermartin** [comment]
I can confirm this bug and it's still not fixed.

It seems the variable `options.ftp.gitftpignore` in [line 163](https://github.com/ezyang/git-ftp/blob/master/git-ftp.py#L163) is set to `None` when the interactive configuration finished. I'm pretty sure this can be resolved by setting `options.ftp.gitftpignore` to a default value solves the error. A close look into the code reveals that the function get_ftp_creds() does only set a default value if the config file exists, which explains the symptoms.

Maybe I'll prepare a pull request, but this project seems somewhat dead, so I have no hope it will get merged, which would be a waste of time.
